# MengRain & Coldvvater-Config   (Stash)
# Date:2022.10.5
# 最后一次更新于：2023.07.14
# Author: MengRain、Coldvvater
#（我的TG频道：https://t.me/mengyulianmian  可从频道进群交流）
# 下载配置后,请手动添加机场订阅
# 找到 {远程订阅} 部分，将MyProxy 部分的 url替换为自己的机场订阅链接  

#混合端口
mixed-port: 7890
#允许局域网
allow-lan: true
#绑定地址
bind-address: '*'
#模式:rule（规则） / global（全局代理）/ direct（全局直连）
mode: Rule
#日志级别（日志输出级别：分级如后silent / info / warning / error / debug级别越高日志输出量越大）
log-level: info
#外部控制器
external-controller: 127.0.0.1:9090

#DNS设置
dns:
  enable: true
  listen: 0.0.0.0:1053
  #DNS服务器
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114
  #DoH服务器
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.dns.sb/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  #列表中的域名将不会被解析为fake ip，这些域名相关的解析请求将会返回它们真实的IP地址
  fake-ip-filter:
    - '+.lan'
    - localhost.ptlogin2.qq.com
    - '*.battle.net'
    - '*.blzstatic.cn'
    - '*.battlenet.com'
    - '*.battlenet.com.cn'
    - 'lens.l.google.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.*.microsoft.com'
    - 'xbox.*.microsoft.com'         
    - '+.msftconnecttest.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - '*.mcdn.bilivideo.cn'

#本地代理
proxies:

#远程订阅
proxy-providers:

  MyProxy:
    url: "https://sub.store/download/collection/MySub"
    # 使用Clash类型订阅链接替换掉引号""内的链接使用。
    # 或可使用通用订阅链接通过Sub-Store进行订阅转换(用于Stash)。
    interval: 86400
    health-check:
      enable: true
      interval: 300
      url: http://www.apple.com/library/test/success.html

#策略组
proxy-groups:

  - name: Proxy
    type: select
    use:
      - MyProxy
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png

  - name: 自动选择
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    use: 
       - MyProxy
    url: "http://www.apple.com/library/test/success.html"
    interval: 300

  - name: Fallback
    type: fallback
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Available.png
    use:
      - MyProxy
    url: "http://www.apple.com/library/test/success.html"
    interval: 300

  - name: US 美国
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    use:
      - MyProxy
    filter: 美|🇺🇲|US|(?i)States|American
    url: "http://www.apple.com/library/test/success.html"
    interval: 300

  - name: HK 香港
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    use:
      - MyProxy
    filter: 港|🇭🇰|HK|(?i)Hong
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
  
  - name: JP 日本
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    use:
      - MyProxy
    filter: 日|🇯🇵|东京|JP|(?i)Japan
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
  
  - name: TW 台湾
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png
    use:
      - MyProxy
    filter: 台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
  
  - name: SG 新加坡
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png
    use:
      - MyProxy
    filter: 新加坡|坡|狮城|🇸🇬|SG|(?i)Singapore
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
  
  - name: 全球
    type: select
    proxies: &G
      - Proxy
      - 自动选择
      - Fallback
      - US 美国
      - HK 香港
      - JP 日本
      - TW 台湾
      - SG 新加坡
      - 漏网之鱼
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/World_Map.png
  
  - name: 国外媒体
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Media.png
  
  - name: Netflix
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
  
  - name: Disney+
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Disney.png
  
  - name: HBO
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/HBO.png
  
  - name: Youtube
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
  
  - name: Spotify
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png
  
  - name: TikTok
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png
  
  - name: Bilibili
    type: select
    proxies:
      - DIRECT
      - HK 香港
      - TW 台湾
    icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Bilibili.png
  
  - name: Telegram
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png

  - name: Clubhouse
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Clubhouse_1.png
  
  - name: Twitter
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
  
  - name: Speedtest
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Speedtest.png
  
  - name: PayPal
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/PayPal.png
  
  - name: TestFlight
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TestFlight.png
  
  - name: Apple
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
  
  - name: Google
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google.png
  
  - name: Microsoft
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
  
  - name: Weibo
    type: select
    proxies:
      *G
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Weibo.png

  - name: OpenAI
    type: select
    proxies:
      *G
    icon: https://gitlab.com/lodepuly/iconlibrary/-/raw/master/Website_icon/80px/OpenAI.png
  
  - name: 中国大陆
    type: select
    proxies:
      - DIRECT
      - Proxy
      - 自动选择
      - Fallback
      - US 美国
      - HK 香港
      - JP 日本
      - TW 台湾
      - SG 新加坡
      - 漏网之鱼
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Heart.png
  
  - name: 漏网之鱼
    type: select
    proxies:
      - Proxy
      - DIRECT
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Pig.png

#远程规则集合
rule-providers:

  OpenAI-rules:
    behavior: classical
    interval: 86400
    name: ChatGPT
    url: https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Stash/RuleSet/OpenAI.yaml
    
  Netflix-rules:
    behavior: classical
    interval: 86400
    name: Netflix
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Netflix/Netflix.yaml

  Disney-rules:
    behavior: classical
    interval: 86400
    name: Disney
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Disney/Disney.yaml

  HBO-rules:
    behavior: classical
    interval: 86400
    name: HBO
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/HBO/HBO.yaml

  Youtube-rules:
    behavior: classical
    interval: 86400
    name: Youtube
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/YouTube/YouTube.yaml

  Spotify-rules:
    behavior: classical
    interval: 86400
    name: Spotify
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Spotify/Spotify.yaml

  TikTok-rules:
    behavior: classical
    interval: 86400
    name: TikTok
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/TikTok/TikTok.yaml

  Bilibili-rules:
    behavior: classical
    interval: 86400
    name: Bilibili
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/BiliBili/BiliBili.yaml

  Telegram-rules:
    behavior: classical
    interval: 86400
    name: Telegram
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Telegram/Telegram.yaml

  Clubhouse-rules:
    behavior: classical
    interval: 86400
    name: Clubhouse
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Clubhouse/Clubhouse.yaml

  ClubhouseIP-rules:
    behavior: classical
    interval: 86400
    name: ClubhouseIP
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ClubhouseIP/ClubhouseIP.yaml

  GitHub-rules:
    behavior: classical
    interval: 86400
    name: GitHub
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml

  Gitlab-rules:
    behavior: classical
    interval: 86400
    name: Gitlab
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitLab/GitLab.yaml

  Twitter-rules:
    behavior: classical
    interval: 86400
    name: Twitter
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Twitter/Twitter.yaml

  Speedtest-rules:
    behavior: classical
    interval: 86400
    name: Speedtest
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Speedtest/Speedtest.yaml

  PayPal-rules:
    behavior: classical
    interval: 86400
    name: PayPal
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/PayPal/PayPal.yaml

  TestFlight-rules:
    behavior: classical
    interval: 86400
    name: TestFlight
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/TestFlight/TestFlight.yaml

  Apple-rules:
    behavior: classical
    interval: 86400
    name: Apple
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Apple/Apple.yaml

  Google-rules:
    behavior: classical
    interval: 86400
    name: Google
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Google/Google.yaml

  Microsoft-rules:
    behavior: classical
    interval: 86400
    name: Microsoft
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Microsoft/Microsoft.yaml

  Weibo-rules:
    behavior: classical
    interval: 86400
    name: Weibo
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Weibo/Weibo.yaml

  Mainland-rules:
    behavior: classical
    interval: 86400
    name: Mainland
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/China/China.yaml

  MainlandIP-rules:
    behavior: ipcidr
    interval: 86400
    name: MainlandIP
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ChinaIPs/ChinaIPs_IP.yaml

  Global-rules:
    behavior: classical
    interval: 86400
    name: Outside
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Global/Global_Classical.yaml

#分流规则引用
rules:
rules:
  - RULE-SET,OpenAI-rules,OpenAI,no-resolve
  - RULE-SET,Netflix-rules,Netflix,no-resolve
  - RULE-SET,Disney-rules,Disney+,no-resolve
  - RULE-SET,HBO-rules,HBO,no-resolve
  - RULE-SET,Youtube-rules,Youtube,no-resolve
  - RULE-SET,Spotify-rules,Spotify,no-resolve
  - RULE-SET,TikTok-rules,TikTok,no-resolve
  - RULE-SET,Bilibili-rules,Bilibili,no-resolve
  - RULE-SET,Telegram-rules,Telegram,no-resolve
  - RULE-SET,Clubhouse-rules,Clubhouse,no-resolve
  - RULE-SET,ClubhouseIP-rules,Clubhouse,no-resolve
  - RULE-SET,GitHub-rules,Proxy,no-resolve
  - RULE-SET,Gitlab-rules,Proxy,no-resolve
  - RULE-SET,Twitter-rules,Twitter,no-resolve
  - RULE-SET,Speedtest-rules,Speedtest,no-resolve
  - RULE-SET,PayPal-rules,PayPal,no-resolve
  - RULE-SET,TestFlight-rules,TestFlight,no-resolve
  - RULE-SET,Apple-rules,Apple,no-resolve
  - RULE-SET,Google-rules,Google,no-resolve
  - RULE-SET,Microsoft-rules,Microsoft,no-resolve
  - RULE-SET,Weibo-rules,Weibo,no-resolve
  - RULE-SET,Global-rules,Proxy,no-resolve
  - RULE-SET,Mainland-rules,中国大陆,no-resolve
  - RULE-SET,MainlandIP-rules,中国大陆
  - GEOIP,CN,DIRECT
  - MATCH,漏网之鱼
